BEGIN;

-- ============================================================
-- BANDS
-- ============================================================

CREATE TABLE bands (
    band_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    band_name TEXT NOT NULL,
    slug TEXT,

    hometown TEXT DEFAULT 'Perth',
    state_region TEXT DEFAULT 'Western Australia',
    country_code TEXT DEFAULT 'AU',

    member_count INTEGER,
    formation_year INTEGER,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'inactive',
                'hiatus',
                'unknown'
            )
        ),

    short_description TEXT,
    internal_notes TEXT,

    is_our_band BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,

    booking_contact_name TEXT,
    contact_email TEXT,
    facebook_url TEXT,
    instagram_url TEXT,
    website_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    archived_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_bands_name_active
ON bands (LOWER(band_name))
WHERE archived_at IS NULL;


-- ============================================================
-- VENUES
-- ============================================================

CREATE TABLE venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    venue_name TEXT NOT NULL,
    slug TEXT,

    suburb TEXT,
    state_region TEXT NOT NULL DEFAULT 'Western Australia',
    country_code TEXT NOT NULL DEFAULT 'AU',

    address TEXT,

    capacity INTEGER,
    venue_type TEXT,

    website_url TEXT,
    booking_url TEXT,
    booking_email TEXT,

    short_description TEXT,
    internal_notes TEXT,

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'inactive',
                'closed',
                'unknown'
            )
        ),

    is_verified BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    archived_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_venues_name_active
ON venues (LOWER(venue_name))
WHERE archived_at IS NULL;

CREATE INDEX idx_venues_suburb
ON venues (suburb);

CREATE INDEX idx_venues_status
ON venues (status);


-- ============================================================
-- GIGS
-- ============================================================

CREATE TABLE gigs (
    gig_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    venue_id BIGINT,

    gig_date TIMESTAMPTZ NOT NULL,

    event_name TEXT,
    notes TEXT,

    status TEXT NOT NULL DEFAULT 'confirmed'
        CHECK (
            status IN (
                'tentative',
                'confirmed',
                'completed',
                'cancelled'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_gigs_venue
        FOREIGN KEY (venue_id)
        REFERENCES venues (venue_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_gigs_venue
ON gigs (venue_id);

CREATE INDEX idx_gigs_date
ON gigs (gig_date);


-- ============================================================
-- GIG BANDS / LINEUPS
-- ============================================================

CREATE TABLE gig_bands (
    gig_id BIGINT NOT NULL,
    band_id BIGINT NOT NULL,

    billing_order INTEGER,
    role TEXT,

    PRIMARY KEY (gig_id, band_id),

    CONSTRAINT fk_gig_bands_gig
        FOREIGN KEY (gig_id)
        REFERENCES gigs (gig_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_gig_bands_band
        FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE
);


-- ============================================================
-- DRINK RIDER TOKENS
-- ============================================================

CREATE TABLE gig_band_drink_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    gig_id BIGINT NOT NULL,
    band_id BIGINT NOT NULL,

    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMPTZ,

    CONSTRAINT fk_drink_tokens_gig
        FOREIGN KEY (gig_id)
        REFERENCES gigs (gig_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_drink_tokens_band
        FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_drink_tokens_gig_band
ON gig_band_drink_tokens (
    gig_id,
    band_id
);


-- ============================================================
-- GENRES
-- ============================================================

CREATE TABLE genres (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    genre_name TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_genres_name
ON genres (LOWER(genre_name));


-- ============================================================
-- BAND GENRES
-- ============================================================

CREATE TABLE band_genres (
    band_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    PRIMARY KEY (band_id, genre_id),

    CONSTRAINT fk_band_genres_band
        FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_band_genres_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
        ON DELETE CASCADE
);


-- ============================================================
-- INITIAL GENRES
-- ============================================================

INSERT INTO genres (genre_name)
VALUES
    ('Rock'),
    ('Pop'),
    ('Indie'),
    ('Metal'),
    ('Punk'),
    ('Blues'),
    ('Jazz'),
    ('Folk'),
    ('Country'),
    ('Funk'),
    ('Soul'),
    ('Reggae'),
    ('Ska'),
    ('Goth'),
    ('Grunge'),
    ('Shoegaze'),
    ('Hardcore'),
    ('Techno'),
    ('Hip-Hop'),
    ('Ambient'),
    ('Electronic'),
    ('Alternative'),
    ('Experimental')
ON CONFLICT DO NOTHING;

COMMIT;