BEGIN;

CREATE TABLE IF NOT EXISTS band_calendar_connections (
    connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id BIGINT NOT NULL,
    provider TEXT NOT NULL CHECK (provider IN ('google')),
    provider_account_id TEXT,
    email TEXT,
    encrypted_refresh_token TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Australia/Perth',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_band_calendar_connections_band
        FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_band_calendar_provider
        UNIQUE (band_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_band_calendar_connections_band
ON band_calendar_connections (band_id);

COMMIT;
