-- ============================================================
-- SupportScout
-- PR contacts / campaign management
-- ============================================================


-- ------------------------------------------------------------
-- PR CONTACTS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pr_contacts (
    pr_contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    outlet VARCHAR(255) NOT NULL,

    language VARCHAR(100),

    contact_name VARCHAR(255),

    email VARCHAR(320),

    contact_type VARCHAR(100),

    location VARCHAR(255),

    best_pitch TEXT,

    summary TEXT,

    source_url TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_pr_contacts_outlet
    ON pr_contacts (LOWER(outlet));

CREATE INDEX IF NOT EXISTS idx_pr_contacts_email
    ON pr_contacts (LOWER(email));

CREATE INDEX IF NOT EXISTS idx_pr_contacts_active
    ON pr_contacts (is_active);


-- ------------------------------------------------------------
-- PR CAMPAIGNS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pr_campaigns (
    pr_campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    subject VARCHAR(500) NOT NULL,

    email_body TEXT NOT NULL,

    attachment_filename VARCHAR(255),

    attachment_path TEXT,

    status VARCHAR(50) NOT NULL DEFAULT 'draft',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    sent_at TIMESTAMPTZ,

    CONSTRAINT chk_pr_campaign_status
        CHECK (
            status IN (
                'draft',
                'sending',
                'sent',
                'partially_sent',
                'failed'
            )
        )
);


-- ------------------------------------------------------------
-- CAMPAIGN RECIPIENTS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pr_campaign_recipients (
    pr_campaign_recipient_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pr_campaign_id BIGINT NOT NULL,

    pr_contact_id BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'pending',

    sent_at TIMESTAMPTZ,

    error_message TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_pr_campaign_recipient_campaign
        FOREIGN KEY (pr_campaign_id)
        REFERENCES pr_campaigns(pr_campaign_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pr_campaign_recipient_contact
        FOREIGN KEY (pr_contact_id)
        REFERENCES pr_contacts(pr_contact_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_pr_campaign_recipient
        UNIQUE (
            pr_campaign_id,
            pr_contact_id
        ),

    CONSTRAINT chk_pr_campaign_recipient_status
        CHECK (
            status IN (
                'pending',
                'sending',
                'sent',
                'failed',
                'skipped'
            )
        )
);


CREATE INDEX IF NOT EXISTS idx_pr_campaign_recipients_campaign
    ON pr_campaign_recipients (pr_campaign_id);

CREATE INDEX IF NOT EXISTS idx_pr_campaign_recipients_contact
    ON pr_campaign_recipients (pr_contact_id);

CREATE INDEX IF NOT EXISTS idx_pr_campaign_recipients_status
    ON pr_campaign_recipients (status);