CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_bands (
    user_id BIGINT NOT NULL,
    band_id BIGINT NOT NULL,
    relationship TEXT NOT NULL DEFAULT 'member',

    PRIMARY KEY (user_id, band_id),

    FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE
);

CREATE TABLE user_calendar_connections (
    connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider TEXT NOT NULL CHECK (provider IN ('google')),
    provider_account_id TEXT,
    email TEXT,
    encrypted_refresh_token TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Australia/Perth',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    UNIQUE (user_id, provider)
);