BEGIN;

DROP TABLE IF EXISTS band_calendar_connections;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_bands (
    user_id BIGINT NOT NULL,
    band_id BIGINT NOT NULL,
    relationship TEXT NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, band_id),

    CONSTRAINT fk_user_bands_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_bands_band
        FOREIGN KEY (band_id)
        REFERENCES bands (band_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_calendar_connections (
    connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider TEXT NOT NULL CHECK (provider IN ('google')),
    provider_account_id TEXT,
    email TEXT,
    encrypted_refresh_token TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Australia/Perth',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_calendar_connections_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_user_calendar_provider
        UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_user_bands_band
ON user_bands (band_id);

CREATE INDEX IF NOT EXISTS idx_user_calendar_connections_user
ON user_calendar_connections (user_id);

COMMIT;