CREATE TABLE rehearsal_proposals (
    proposal_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    band_id BIGINT NOT NULL
        REFERENCES bands(band_id)
        ON DELETE CASCADE,

    proposed_by_user_id BIGINT NOT NULL
        REFERENCES users(user_id)
        ON DELETE RESTRICT,

    start_at TIMESTAMPTZ NOT NULL,

    end_at TIMESTAMPTZ NOT NULL,

    location TEXT,

    notes TEXT,

    status TEXT NOT NULL
        DEFAULT 'proposed'
        CHECK (
            status IN (
                'proposed',
                'confirmed',
                'cancelled'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    CHECK (
        end_at > start_at
    )
);

CREATE INDEX
    idx_rehearsal_proposals_band_start
ON rehearsal_proposals (
    band_id,
    start_at
);

CREATE INDEX
    idx_rehearsal_proposals_proposer
ON rehearsal_proposals (
    proposed_by_user_id
);