CREATE TABLE rehearsal_locations (
    rehearsal_location_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name TEXT NOT NULL,

    address TEXT,
    suburb TEXT,
    state TEXT NOT NULL DEFAULT 'WA',
    postcode TEXT,

    phone TEXT,
    email TEXT,
    website TEXT,
    booking_url TEXT,

    default_session_minutes INTEGER,

    indicative_rate NUMERIC(10, 2),

    notes TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE band_rehearsal_locations (
    band_id BIGINT NOT NULL
        REFERENCES bands(band_id)
        ON DELETE CASCADE,

    rehearsal_location_id BIGINT NOT NULL
        REFERENCES rehearsal_locations(
            rehearsal_location_id
        )
        ON DELETE CASCADE,

    is_favourite BOOLEAN NOT NULL DEFAULT FALSE,

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (
        band_id,
        rehearsal_location_id
    )
);

ALTER TABLE rehearsal_proposals
ADD COLUMN rehearsal_location_id BIGINT
    REFERENCES rehearsal_locations(
        rehearsal_location_id
    )
    ON DELETE SET NULL;

CREATE INDEX
    idx_band_rehearsal_locations_band
ON band_rehearsal_locations (
    band_id
);

CREATE INDEX
    idx_rehearsal_locations_name
ON rehearsal_locations (
    name
);

CREATE INDEX
    idx_rehearsal_proposals_location
ON rehearsal_proposals (
    rehearsal_location_id
);

INSERT INTO rehearsal_locations (
    name,
    suburb,
    state,
    phone,
    email,
    website,
    notes
)
VALUES
(
    'The Hen House Rehearsal Studios',
    'Osborne Park',
    'WA',
    '0407 442 726',
    'bookings@thehenhouse.com.au',
    'https://thehenhouse.com.au',
    'Perth rehearsal studio. Current source lists Unit 3 and Unit 10 Rowallan St, Osborne Park.'
),
(
    'Emerald Room Studios',
    'Balcatta',
    'WA',
    NULL,
    NULL,
    'https://emeraldroomstudios.com.au',
    'Recording and rehearsal studios in Perth. Soundproof rehearsal rooms with PA equipment.'
),
(
    'Vision Studios',
    'East Victoria Park',
    'WA',
    '0432 034 122',
    'info@visionstudios.com.au',
    'https://www.visionstudios.com.au',
    'Rehearsal and recording studios. Regular Red Temples Tuesday rehearsal location.'
);

INSERT INTO band_rehearsal_locations (
    band_id,
    rehearsal_location_id,
    is_favourite,
    notes
)
SELECT
    12,
    rehearsal_location_id,
    TRUE,
    'Regular Tuesday rehearsal location'
FROM rehearsal_locations
WHERE name = 'Vision Studios'
ON CONFLICT (
    band_id,
    rehearsal_location_id
)
DO UPDATE SET
    is_favourite = TRUE,
    notes = EXCLUDED.notes;

UPDATE rehearsal_locations
SET
    address = '4/12 Milford St',
    suburb = 'East Victoria Park',
    state = 'WA',
    postcode = '6101',
    updated_at = NOW()
WHERE name = 'Vision Studios';